name = "WavePropBase"
uuid = "91c5bd54-65f5-4719-ae3b-9579edfc4a0b"
authors = ["Luiz M. Faria <maltezfaria@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.2"
julia = "1.6"
